### PR TITLE
Handle formatting []byte

### PR DESCRIPTION
**Pull request by icholy**

### CODE REVIEW

**Comment by novln** [comment]
Could you give us an example with `[]byte` ?
We are not sure that you need to escape the value inside `'`, but we could be wrong.

Anyway, thanks for the pull request.

**Comment by icholy** [comment]
@novln `[]byte` is one of the types that `database/sql` supports see: https://golang.org/pkg/database/sql/#Scanner 
I use it all the time. For example, all the hashing functions in the standard library return byte slices, and I'm used to just passing those in rather than casting them to a string.

**Comment by icholy** [comment]
@novln in regards to the escaping, this is directly related to the issue i opened.

**Comment by icholy** [comment]
We can also do this for the bytes

``` go
import (
	"encoding/hex"
	"fmt"
)

func Bytes(value []byte) string {
	return `'\\x` + hex.EncodeToString(value) + `'`
}
```

**Pull request merged**
