### PR TITLE
Loukoum v3

### PR DESCRIPTION
**Pull request by novln**
## Changelog

 * Add NOT EXISTS subquery
 * Add support of go modules
 * Break compatibility with dep

**Include:**

 * #67
 * #70

>**NOTE**: Please ask in issues if you require a `dep` backports.

### CODE REVIEW

**Comment by thoas** [comment]
@novln any blocker on your side, to release it?

**Comment by novln** [comment]
@thoas Not at all: we can merge right now 🙂

**Comment by thoas** [comment]
@novln let's go 🚀

**Comment by thoas** [comment]
👏

**Pull request merged**
